baseURL = 'https://Lauphie.github.io/Blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "paper"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  name = "Philipp"
  bio = "Kurzbeschreibung"